-- SUPERSEDED / NEUTRALIZED (05-21). DO NOT RE-ENABLE.
--
-- This migration was a FLAWED attempt to fix unconverted foreign-currency
-- recurring drafts. SQL cannot call FX, so the original UPDATE could not
-- actually convert anything — it merely relabeled `currency_original` from the
-- rule's foreign currency to the budget default on the rate-1 (UNCONVERTED)
-- amounts. That made the drafts *look* budget-currency while still holding the
-- foreign magnitude (e.g. "3500 PLN" surfaced as "3500 EUR"), and it CORRUPTED
-- `currency_original` so the draft row could no longer be trusted.
--
-- The correct fix is a re-conversion SCRIPT that re-derives each unconfirmed
-- recurring draft from its RULE (the source of truth) and converts through the
-- REAL FrankfurterFxProvider:
--   scripts/backfill-recurring-draft-fx.ts   (05-21, run-and-delete data fix)
-- plus a stub guard so the rate-1 InMemoryFxProvider can never reach a write
-- path again (InMemoryFxProvider.rateAsOf now THROWS on unseeded cross-currency).
--
-- The original body toggled FORCE ROW LEVEL SECURITY off/on around a
-- cross-tenant UPDATE/JOIN (the migrator role is NOBYPASSRLS and both tables are
-- FORCE'd, so a plain migrator UPDATE sees 0 rows). Re-running it on a FRESH DB
-- would re-introduce the relabel corruption on any rate-1 draft, so the body is
-- intentionally a no-op now. The journal entry (idx 31) is preserved to avoid
-- churning drizzle/meta; this file is kept as a tombstone documenting the
-- superseded approach.
--
-- Intentional no-op (a bare SELECT keeps drizzle-kit happy without mutating).
--> statement-breakpoint
SELECT 1;
