/**
 * tasks-schema.ts — Drizzle schema for budgeting.tasks (NEW in v1.1)
 * RLS via pgPolicy. FORCE RLS in post-migration.sql.
 * No domain imports — adapters only.
 *
 * Tasks are action-queue items generated by Phase 7 generators (RESERVE_TOPUP,
 * CONFIRM_DRAFT, STALE_WALLET, MONTH_END_REVIEW). Phase 1 creates the empty table.
 * FK budget_id → tenancy.budgets(id) ON DELETE CASCADE and composite index
 * (budget_id, status) are in the SQL migration (plan analogy: category_limits_pit_idx).
 */
import { sql } from "drizzle-orm";
import {
  pgPolicy,
  uuid,
  text,
  jsonb,
  timestamp,
  check,
} from "drizzle-orm/pg-core";
import { budgeting, appRole, workerRole } from "@budget/platform";

export const tasks = budgeting.table(
  "tasks",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id").notNull(),
    budgetId: uuid("budget_id").notNull(),
    kind: text("kind").notNull(),
    payloadJson: jsonb("payload_json").notNull().default({}),
    status: text("status").notNull().default("PENDING"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    resolvedAt: timestamp("resolved_at", { withTimezone: true }),
  },
  (t) => [
    check(
      "tasks_kind_chk",
      sql`${t.kind} IN ('RESERVE_TOPUP','CONFIRM_DRAFT','STALE_WALLET','MONTH_END_REVIEW')`,
    ),
    check("tasks_status_chk", sql`${t.status} IN ('PENDING','RESOLVED')`),
    pgPolicy("tasks_tenant_isolation", {
      as: "permissive",
      for: "all",
      to: [appRole, workerRole],
      using: sql`${t.tenantId} = ANY(coalesce(nullif(current_setting('app.tenant_ids', true), ''), '{}')::uuid[])`,
      withCheck: sql`${t.tenantId} = ANY(coalesce(nullif(current_setting('app.tenant_ids', true), ''), '{}')::uuid[])`,
    }),
  ],
);
