import { Pool } from "pg";
import { drizzle } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { resetPools } from "@budget/platform";

/**
 * PC-06: Idempotent testcontainer bootstrap. Wave-1 + Wave-2 integration tests call this in
 * beforeAll(); the container starts once per test process. Replaces the former
 * skipIf(!process.env.DATABASE_URL_APP) gate so tests run for real in CI without docker compose.
 *
 * PC-28: This file is the SOLE approved raw-client (`new Pool` + `.query`) call site within
 * tests/ — whitelisted by Plan 00's `--exclude-dir=test` grep gate. Pre-migration bootstrap
 * has no GUC to set, so withInfraTx / withUserContext are not applicable here.
 *
 * PC-29: The drizzle `migrate()` call below READS the generated SQL files in `drizzle/`. Those
 * files are GENERATED by Plan 06's close-out task (`bunx drizzle-kit generate`). The
 * testcontainer is a CONSUMER of generated migrations, not a producer. If the directory is
 * empty, migrate() will run no-op and the post-migration.sql will fail when it tries to GRANT
 * on tables that don't exist — that is the correct fail-fast behavior, surfacing that Wave-2
 * tests were started before Plan 06's generate task ran.
 *
 * Implementation note: uses `docker run` directly via Bun.spawn instead of the
 * @testcontainers/postgresql library due to Bun event-loop compatibility issues with
 * testcontainers v10 (the library uses Node.js-specific async patterns that prevent Bun
 * from detecting pending work, causing premature process exit). Bun.spawn is the idiomatic
 * Bun-native approach.
 */

// Docker label applied to every test container so leaked containers can be
// found and removed by tooling (`make test:clean`) and the signal handlers
// installed below if a test process is killed before stopTestcontainer() runs.
const TESTCONTAINER_LABEL = "budget-testcontainer=1";

let bootedPromise: Promise<void> | undefined;
let containerId: string | undefined;
let signalHandlersInstalled = false;

function installSignalHandlers(): void {
  if (signalHandlersInstalled) return;
  signalHandlersInstalled = true;
  const cleanup = (signal: NodeJS.Signals) => {
    if (containerId) {
      const id = containerId;
      containerId = undefined;
      try {
        Bun.spawnSync(["docker", "rm", "-f", id], {
          stdout: "ignore",
          stderr: "ignore",
        });
      } catch {
        /* best effort */
      }
    }
    process.exit(signal === "SIGINT" ? 130 : 143);
  };
  process.on("SIGINT", cleanup);
  process.on("SIGTERM", cleanup);
  process.on("SIGHUP", cleanup);
}

async function runCmd(cmd: string[]): Promise<string> {
  const proc = Bun.spawn(cmd, { stdout: "pipe", stderr: "pipe" });
  const out = await new Response(proc.stdout).text();
  const exitCode = await proc.exited;
  if (exitCode !== 0) {
    const errText = await new Response(proc.stderr).text();
    throw new Error(
      `Command failed (${exitCode}): ${cmd.join(" ")}\n${errText}`,
    );
  }
  return out.trim();
}

export async function startTestcontainer(): Promise<{
  urlApp: string;
  urlWorker: string;
  urlMigrator: string;
}> {
  if (bootedPromise) {
    await bootedPromise;
  } else {
    installSignalHandlers();
    bootedPromise = (async () => {
      // Start postgres:17-alpine container with a random port and built-in healthcheck
      containerId = await runCmd([
        "docker",
        "run",
        "--rm",
        "-d",
        "--label",
        TESTCONTAINER_LABEL,
        "-e",
        "POSTGRES_PASSWORD=postgres",
        "-e",
        "POSTGRES_USER=postgres",
        "-e",
        "POSTGRES_DB=budget",
        "-p",
        "0:5432",
        "--health-cmd",
        "pg_isready -U postgres",
        "--health-interval",
        "1s",
        "--health-timeout",
        "5s",
        "--health-retries",
        "20",
        "postgres:17-alpine",
      ]);

      // Wait for the container to be healthy (pg_isready)
      let attempts = 0;
      while (attempts < 40) {
        const status = await runCmd([
          "docker",
          "inspect",
          "--format",
          "{{.State.Health.Status}}",
          containerId,
        ]).catch(() => "starting");
        if (status === "healthy") break;
        await new Promise((r) => setTimeout(r, 1000));
        attempts++;
      }
      if (attempts >= 40)
        throw new Error("Postgres container did not become healthy in 40s");

      // Get the mapped port
      const portMapping = await runCmd([
        "docker",
        "inspect",
        "--format",
        '{{(index (index .NetworkSettings.Ports "5432/tcp") 0).HostPort}}',
        containerId,
      ]);
      const port = portMapping.trim();
      const host = "127.0.0.1";

      const adminUrl = `postgresql://postgres:postgres@${host}:${port}/budget`;
      const adminPool = new Pool({ connectionString: adminUrl });

      // Create the three application roles (NOBYPASSRLS) — PC-28 raw-client carve-out
      // Pre-migration bootstrap has no GUC to set; withInfraTx not applicable here.
      try {
        await adminPool.query(
          `CREATE ROLE app_role LOGIN PASSWORD 'app_pwd' NOBYPASSRLS NOSUPERUSER NOCREATEDB NOCREATEROLE`,
        );
        await adminPool.query(
          `CREATE ROLE worker_role LOGIN PASSWORD 'worker_pwd' NOBYPASSRLS NOSUPERUSER NOCREATEDB NOCREATEROLE`,
        );
        await adminPool.query(
          `CREATE ROLE migrator LOGIN PASSWORD 'migrator_pwd' NOBYPASSRLS NOSUPERUSER CREATEDB NOCREATEROLE`,
        );
        // Schemas (D-17)
        await adminPool.query(
          `CREATE SCHEMA IF NOT EXISTS identity AUTHORIZATION migrator`,
        );
        await adminPool.query(
          `CREATE SCHEMA IF NOT EXISTS tenancy AUTHORIZATION migrator`,
        );
        await adminPool.query(
          `CREATE SCHEMA IF NOT EXISTS shared_kernel AUTHORIZATION migrator`,
        );
        await adminPool.query(
          `CREATE SCHEMA IF NOT EXISTS comparison AUTHORIZATION migrator`,
        );
        await adminPool.query(
          `CREATE SCHEMA IF NOT EXISTS budgeting AUTHORIZATION migrator`,
        );
        // Grant migrator schema ownership for DDL
        await adminPool.query(`GRANT CREATE ON DATABASE budget TO migrator`);
        await adminPool.query(
          `GRANT ALL ON SCHEMA identity, tenancy, shared_kernel, comparison, budgeting TO migrator`,
        );
        // PG15+ revokes default CREATE on the public schema. Drizzle migrations
        // generate types/tables in the public schema (e.g. audit_action enum,
        // pg-boss queue tables in production), so the migrator role needs CREATE
        // on it during testcontainer bootstrap. Production grants this in
        // infra/postgres/init/02-grants.sql.
        await adminPool.query(`GRANT ALL ON SCHEMA public TO migrator`);
      } finally {
        await adminPool.end();
      }

      const urlApp = `postgresql://app_role:app_pwd@${host}:${port}/budget`;
      const urlWorker = `postgresql://worker_role:worker_pwd@${host}:${port}/budget`;
      const urlMigrator = `postgresql://migrator:migrator_pwd@${host}:${port}/budget`;

      process.env.DATABASE_URL_APP = urlApp;
      process.env.DATABASE_URL_WORKER = urlWorker;
      process.env.DATABASE_URL_MIGRATOR = urlMigrator;

      // Reset pool singletons so they pick up the new DATABASE_URL_* values set above.
      resetPools();

      // PC-29: Read & apply the migrations that Plan 06's close-out task GENERATED.
      // We do NOT run drizzle-kit generate here — generation is Plan 06's responsibility.
      // drizzle migrations are run as migrator; post-migration.sql ALTER ROLE statements
      // require superuser, so we run them via the admin pool.
      const migPool = new Pool({ connectionString: urlMigrator });
      const db = drizzle(migPool);
      try {
        await migrate(db, {
          migrationsFolder: resolve(process.cwd(), "drizzle"),
        });
      } finally {
        await migPool.end();
      }

      // Apply post-migration.sql via admin (postgres) — ALTER ROLE requires superuser
      const adminPool2 = new Pool({ connectionString: adminUrl });
      try {
        const post = readFileSync(
          resolve(process.cwd(), "apps/migrator/post-migration.sql"),
          "utf8",
        );
        await adminPool2.query(post);
      } finally {
        await adminPool2.end();
      }
    })();
    await bootedPromise;
  }

  return {
    urlApp: process.env.DATABASE_URL_APP!,
    urlWorker: process.env.DATABASE_URL_WORKER!,
    urlMigrator: process.env.DATABASE_URL_MIGRATOR!,
  };
}

export async function stopTestcontainer(): Promise<void> {
  if (containerId) {
    await runCmd(["docker", "stop", containerId]).catch(() => undefined);
    containerId = undefined;
    bootedPromise = undefined;
  }
}
